import type { LevelData } from "@shared/schema";

export const levelsData: LevelData[] = [
  {
    id: 1,
    title: "🌍 Dunia Digital",
    subtitle: "Cari Tombol Rahasia Kody",
    description: "Perbaiki tombol ON/OFF, sensor, dan layar Kody!",
    type: "puzzle",
    color: "blue",
    icon: "⚡",
    skills: ["Hardware", "Software", "Sensor Digital"],
    isLocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 2,
    title: "🐍 Negeri Pythonia", 
    subtitle: "Ajari Kody Bahasa Mesin!",
    description: "Tulis kode Python untuk menghidupkan otak Kody!",
    type: "code",
    color: "green", 
    icon: "💻",
    skills: ["Python", "If-Else", "Instruksi"],
    isLocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 3,
    title: "🌐 Webtopia",
    subtitle: "Pasang Wajah Kody di Layar", 
    description: "Buat tampilan wajah dan ekspresi untuk Kody!",
    type: "design",
    color: "orange",
    icon: "🎨", 
    skills: ["HTML", "CSS", "Visual Design"],
    isLocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 4,
    title: "📱 Applandia",
    subtitle: "Bikin Tombol Ajaib Kody",
    description: "Rancang tombol kontrol untuk perintah Kody!",
    type: "ui",
    color: "purple",
    icon: "📱",
    skills: ["UI Design", "Interaksi", "Kontrol"], 
    isLocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 5,
    title: "🤖 Robotron",
    subtitle: "Saatnya Kody Bergerak!",
    description: "Gabungkan semua skill untuk mengontrol Kody!",
    type: "robot",
    color: "red",
    icon: "🤖",
    skills: ["Robotika", "Kontrol", "Integrasi"],
    isLocked: true, 
    isCompleted: false,
    stars: 0,
  },
];
